# Imagen base
FROM python:3.11

# Directorio de trabajo
WORKDIR /app

# Copiar archivos de requerimientos
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar archivos de la aplicación
COPY . .

# Expose ports
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]